name: Publish to pypi
on:
  workflow_dispatch:
  push:
    branches:
      - "main"

    paths:
      - "pytdbot/__init__.py"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: Type check with ty
        run: |
          python -m pip install --upgrade pip ty
          ty check

      - name: Build pytdbot
        run: |
          python -m pip install --upgrade build
          python -m build

      - name: Upload to pypi
        uses: pypa/gh-action-pypi-publish@release/v1
